### ISSUE TITLE
No example of iba data to pandas dataframe.

### ISSUE THREAD

**Issue by Hoffelhas** [mb4u14/steel-disco#1]
Hi there!

On the wiki it says: "Following is an example of how it can be imported into pandas dataframe.", however there does not seem to be any example.

Could it be possible to share more info about this, since this is an issue I'm currently working on.

Thanks in advance.

**Comment by Leodal24** [comment]
Hi!

Also, I try to extract iba dat file in Python, but as your comment, I can't find any example.
Is there any comments or samples I can reference for iba data accessing.

Really thanks for your comment sharing.
